ARG IMAGE_TAG=octez-v20.3

FROM docker.io/tezos/tezos:${IMAGE_TAG}

ARG PROTOCOLS=parisbox

USER root

ENV ASCEND_SERVICES=/ascend/services
ENV ASCEND_HEALTHCHECKS=/ascend/healthchecks
ENV ASCEND_SOCKET=/var/run/ascend.socket
ENV ASCEND_LOGS=/ascend/logs
ENV ASCEND_INIT="tezbox init --setup-services"
ENV TEZBOX_USER=tezos
ENV HOME=/tezbox/context/data

# dal scripts need curl
RUN apk add curl

RUN printf '#!/bin/sh\n\
if [ -z "$GITHUB_TOKEN" ]; then\n\
  wget "$@" \n\
else\n\
  wget --header "Authorization: token $GITHUB_TOKEN" "$@" \n\
fi\n' > /usr/local/bin/auth_wget && chmod +x /usr/local/bin/auth_wget

# Use auth_wget for downloading files with optional authentication
RUN auth_wget https://raw.githubusercontent.com/alis-is/ascend/main/tools/setup/standalone-linux.sh -O /tmp/setup-ascend.sh && sh /tmp/setup-ascend.sh --prerelease

RUN mkdir -p /tezbox /tezbox/configuration /tezbox/overrides /tezbox/overrides/context
COPY configuration /tezbox/configuration
RUN chown -R tezos:tezos /tezbox

COPY bin/tezbox /usr/bin/tezbox
RUN chmod +x /usr/bin/tezbox
RUN chown -R tezos:nogroup /usr/bin/tezbox

ENV PROTOCOLS=${PROTOCOLS}
RUN echo $PROTOCOLS
ADD tools/cleanup-protocols.lua /tmp/cleanup-protocols.lua
RUN eli /tmp/cleanup-protocols.lua && rm /tmp/cleanup-protocols.lua

USER root
ENTRYPOINT [ "ascend" ]
CMD ["parisbox"]