ARG IMAGE_TAG=octez-v20.3

FROM docker.io/tezos/tezos:${IMAGE_TAG}

ARG PROTOCOLS=parisbox

USER root

ENV ASCEND_SERVICES=/ascend/services
ENV ASCEND_HEALTHCHECKS=/ascend/healthchecks
ENV ASCEND_SOCKET=/var/run/ascend.socket
ENV ASCEND_LOGS=/var/log/ascend
ENV ASCEND_INIT="tezbox init --setup-services"
ENV TEZBOX_USER=tezos
ENV HOME=/tezbox/data

RUN printf '#!/bin/sh\n\
if [ -z "$GITHUB_TOKEN" ]; then\n\
  wget "$@" \n\
else\n\
  wget --header "Authorization: token $GITHUB_TOKEN" "$@" \n\
fi\n' > /usr/local/bin/auth_wget && chmod +x /usr/local/bin/auth_wget

# Use auth_wget for downloading files with optional authentication
RUN auth_wget https://raw.githubusercontent.com/alis-is/ascend/main/tools/setup/standalone-linux.sh -O /tmp/setup-ascend.sh && sh /tmp/setup-ascend.sh --prerelease

# RUN mkdir -p ${ASCEND_HEALTHCHECKS}
# COPY tools/healthchecks/baker ${ASCEND_HEALTHCHECKS}/baker
# RUN chmod +x ${ASCEND_HEALTHCHECKS}/baker

RUN mkdir -p /tezbox /tezbox/configuration /tezbox/overrides /tezbox/overrides/context
COPY configuration /tezbox/configuration
RUN chown -R tezos:tezos /tezbox

COPY bin/tezbox /usr/local/bin/tezbox
RUN chmod +x /usr/local/bin/tezbox
RUN chown -R tezos:nogroup /usr/local/bin/tezbox

ENV PROTOCOLS=${PROTOCOLS}
RUN echo $PROTOCOLS
ADD tools/cleanup-protocols.lua /tmp/cleanup-protocols.lua
RUN eli /tmp/cleanup-protocols.lua && rm /tmp/cleanup-protocols.lua

# RUN if echo "$PROTOCOLS" | grep -q "PsqenaVw"; then \
#   auth_wget https://github.com/tez-capital/tezos/releases/download/qena/octez-node -O /usr/local/bin/octez-node && \
#   chmod +x /usr/local/bin/octez-node; \
# fi

# RUN if echo "$PROTOCOLS" | grep -q "PsqenaVw"; then \
#   auth_wget https://github.com/tez-capital/tezos/releases/download/qena/octez-baker-qena -O /usr/local/bin/octez-baker-PsqenaVw && \
#   chmod +x /usr/local/bin/octez-baker-PsqenaVw; \
# fi

# RUN if echo "$PROTOCOLS" | grep -q "PsqenaVw"; then \
#   auth_wget https://github.com/tez-capital/tezos/releases/download/qena/octez-client -O /usr/local/bin/octez-client && \
#   chmod +x /usr/local/bin/octez-client; \
# fi

USER root
ENTRYPOINT [ "ascend" ]
CMD ["parisbox"]